---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: moviefun-pks-v2
  labels:
    app: moviefun-pks
    version: v2.0
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: moviefun-pks-v2
  targetCPUUtilizationPercentage: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks-v2
  labels:
    app: moviefun-pks
    version: v2.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviefun-pks
      version: v2.0
  template:
    metadata:
      labels:
        app: moviefun-pks
        version: v2.0
    spec:
      containers:
        - name: moviefun-pks
          image: pivotaleducation/moviefun-pks:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 600m
