---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviefun-pks
  template:
    metadata:
      labels:
        app: moviefun-pks
    spec:
      containers:
      - name: moviefun-pks
        image: pivotaleducation/moviefun-pks:2.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: MOVIEFUN_TITLE
          value: "MovieFunFromDeploymentManifest"
